### ISSUE TITLE
Unable to resolve host "bus.wuhancloud.cn". 

### ISSUE THREAD

**Issue by xl-Synapse** [PPeanutButter/BusTracingAppForWuhan#2]
# Garbage! 
**It doesn't work at all.**

<img src="https://user-images.githubusercontent.com/48093475/179567107-569f51c9-69ad-4fe4-8b40-d1fc4f843376.jpg" width = "300"  alt="" align=center />

![6YBATK4VOA3B %S 31S%$6K](https://user-images.githubusercontent.com/48093475/179567138-520f0964-ecec-453c-86fa-9da0bbacaa9d.png)

**Comment by PPeanutButter** [comment]
fixed in 1.0.0
